CREATE TABLE IF NOT EXISTS EMPLOYEES (
EMP_ID INTEGER,
EMP_NAME TEXT,
DEPARTMENT TEXT,
SALARY REAL
);

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPARTMENT, SALARY) VALUES
(1, 'Rahul', 'HR', 25000),
(2, 'Sneha', 'IT', 40000),
(3, 'Aman', 'IT', 45000),
(4, 'Pooja', 'HR', 30000),
(5, 'Ravi', 'Sales', 35000);

SELECT COUNT(*) AS Total_Employees
FROM EMPLOYEES;

SELECT AVG(SALARY) AS Average_Salary
FROM EMPLOYEES;

SELECT SUM(SALARY) AS Total_Salary
FROM EMPLOYEES;

SELECT MAX(SALARY) AS Highest_Salary
FROM EMPLOYEES;

SELECT MIN(SALARY) AS Lowest_Salary
FROM EMPLOYEES;

