CREATE TABLE IF NOT EXISTS STUDENTS (
STUDENT_ID INTEGER,
STUDENT_NAME TEXT,
CLASS TEXT,
MARKS INTEGER
);
INSERT INTO STUDENTS (STUDENT_ID, STUDENT_NAME, CLASS, MARKS) VALUES
(1,'Amit', '10A', 78),
(2,'Neha', '10A', 85),
(3,'Rohan', '10B', 67),
(4,'Priya', '10B', 92),
(5,'Karan', '10A', 74);

SELECT COUNT(*) AS Total_Students
FROM STUDENTS;

SELECT AVG(MARKS) AS Average_Marks
FROM STUDENTS;

SELECT SUM(MARKS) AS Total_Marks
FROM STUDENTS;

SELECT MAX(MARKS) AS Highest_Marks
FROM STUDENTS;

SELECT MIN(MARKS) AS Lowest_Marks
FROM STUDENTS;





